## settings
DATASET_DIR = '/home/doeun/code/AI/ESTSOFT2024/workspace/dataset/'
RAW_DATA_DIR = 'america_big_cities_health_inventory'
RAW_FILE_NAME = 'BigCitiesHealth.csv'
RSLT_DIR = '/home/doeun/code/AI/ESTSOFT2024/workspace/1.project1_structured/BCHI/processed/'
PVTB_DIR = RSLT_DIR + 'pvtb/'

## CONSTANTS - ENCODING/METRIC
entire_region = [ "Midwest", "Northeast", "South", "West" ]
region_adjacent = [
    { "Midwest", "Northeast" },
    { "Midwest", "South" },
    { "Midwest", "West" },
    { "West", "South" },
    { "South", "Northeast" }
]
encode_region ={
    "Midwest": 0,
    "Northeast": 1,
    "South": 2,
    "West": 3 
}

entire_race = ['All','White','Black','Hispanic','Asian/PI','Natives']
race_adjacent = [
    {'All', a}
    for a in entire_race
    if a != 'All'
]
encode_race={
    'All' : 0,
    'White' : 1,
    'Black' : 2,
    'Hispanic' : 3,
    'Asian/PI' : 4,
    'Natives' : 5,
}

entire_sex = ['Both','Female','Male']
sex_adjacent = [
    {'Both', a}
    for a in entire_sex
    if a != 'Both'
]
encode_sex = {
    'Both' : 0,
    'Female' : 1,
    'Male' : 2,
}

encode_poverty = {
    'Poorest cities (18%+ poor)' : 0,
    'Less poor cities (<18% poor)' : 1,
}
encode_pop = {
    'Smaller (<1.3 million)' : 0,
    'Largest (>1.3 million)' : 1,
}
encode_popdensity = {
    'Lower pop. density (<10k per sq mi)' : 0,
    'Highest pop. density (>10k per sq mi)' : 1,
}
encode_segregation = {
    'Less Segregated (<50%)' : 0,
    'Highly Segregated (50%+)' : 1,
}

encode_dict ={
    'strata_race_label': encode_race,
    'strata_sex_label': encode_sex,
    'geo_strata_region' : encode_region,
    'geo_strata_poverty' : encode_poverty,
    'geo_strata_Population' : encode_pop,
    'geo_strata_PopDensity' : encode_popdensity,
    'geo_strata_Segregation' : encode_segregation,
}

info_cols = [ #updated after city type encoding
    'geo_city_type',
    'encoded_strata_race_label',
    'encoded_strata_sex_label',
    'encoded_geo_strata_region',
    'encoded_geo_strata_poverty',
    'encoded_geo_strata_Population',
    'encoded_geo_strata_PopDensity',
    'encoded_geo_strata_Segregation',
    'date_label',
]

geo_strat_cols = [
    'geo_strata_region' ,
    'geo_strata_poverty' ,
    'geo_strata_Population' ,
    'geo_strata_PopDensity' ,
    'geo_strata_Segregation' ,
]

test_cols = [
    'Cancer | All Cancer Deaths',                                
    'Cancer | Lung Cancer Deaths',                               
    'Cancer | Colorectal Cancer Deaths',                         
    'Cardiovascular Disease | Cardiovascular Disease Deaths',    
    'Cardiovascular Disease | Heart Disease Deaths',             
    'Deaths | Deaths from All Causes',                           
    'Deaths | Motor Vehicle Deaths',                             
    'Deaths | Gun Deaths (Firearms)',                            
    'Deaths | Premature Death',                                  
    'Deaths | Injury Deaths',                                    
    'Diabetes and Obesity | Diabetes Deaths',                    
    'Life Expectancy at Birth | Life Expectancy',                
    'Mental Health | Suicide',                                   
    'Respiratory Infection | Pneumonia or Influenza Deaths',     
    'Substance Use | Opioid Overdose Deaths',                    
    'Substance Use | Drug Overdose Deaths',                      
    'Crime Incidents | Homicides',                               
]

col_cand_list=[
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Deaths | Premature Death',
    'Income Inequality | Household Income Inequality',
    'Income | Households with Higher-Incomes',
    'Life Expectancy at Birth | Life Expectancy',
    'Substance Use | Adult Smoking',
    'Births | Preterm Births',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Cardiovascular Disease | Heart Disease Deaths',
    'Deaths | Infant Deaths',
    'Deaths | Premature Death',
    'Income Inequality | Household Income Inequality',
    'Income | Households with Higher-Incomes',
    'Income | Per-capita Household Income',
    'Language and Nativity | Primarily Speak English',
    'Life Expectancy at Birth | Life Expectancy',
    'Substance Use | Adult Smoking',
    'Cancer | All Cancer Deaths',
    'Cancer | Breast Cancer Deaths',
    'Cancer | Lung Cancer Deaths',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Cardiovascular Disease | Heart Disease Deaths',
    'Language and Nativity | Primarily Speak Spanish',
    'Births | Teen Births',
    'Cancer | All Cancer Deaths',
    'Cancer | Breast Cancer Deaths',
    'Cancer | Lung Cancer Deaths',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Cardiovascular Disease | Heart Disease Deaths',
    'Heat and Disasters | Community Social Vulnerability to Climate Disasters',
    'Income-related | Unemployment',
    'Language and Nativity | Primarily Speak Spanish',
    'Mental Health | Suicide',
    'Race/Ethnicity | Minority Population',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Deaths | Premature Death',
    'Income Inequality | Household Income Inequality',
    'Income | Households with Higher-Incomes',
    'Life Expectancy at Birth | Life Expectancy',
    'Substance Use | Adult Smoking',
    'Births | Preterm Births',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Cardiovascular Disease | Heart Disease Deaths',
    'Deaths | Infant Deaths',
    'Deaths | Premature Death',
    'Income Inequality | Household Income Inequality',
    'Income | Households with Higher-Incomes',
    'Income | Per-capita Household Income',
    'Language and Nativity | Primarily Speak English',
    'Life Expectancy at Birth | Life Expectancy',
    'Substance Use | Adult Smoking',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Deaths | Premature Death',
    'Income Inequality | Household Income Inequality',
    'Income | Households with Higher-Incomes',
    'Life Expectancy at Birth | Life Expectancy',
    'Substance Use | Adult Smoking',
    'Births | Preterm Births',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Cardiovascular Disease | Heart Disease Deaths',
    'Deaths | Infant Deaths',
    'Deaths | Premature Death',
    'Income Inequality | Household Income Inequality',
    'Income | Households with Higher-Incomes',
    'Income | Per-capita Household Income',
    'Language and Nativity | Primarily Speak English',
    'Life Expectancy at Birth | Life Expectancy',
    'Substance Use | Adult Smoking',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Deaths | Premature Death',
    'Income Inequality | Household Income Inequality',
    'Income | Households with Higher-Incomes',
    'Life Expectancy at Birth | Life Expectancy',
    'Substance Use | Adult Smoking',
    'Births | Preterm Births',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Cardiovascular Disease | Heart Disease Deaths',
    'Deaths | Infant Deaths',
    'Deaths | Premature Death',
    'Income Inequality | Household Income Inequality',
    'Income | Households with Higher-Incomes',
    'Income | Per-capita Household Income',
    'Language and Nativity | Primarily Speak English',
    'Life Expectancy at Birth | Life Expectancy',
    'Substance Use | Adult Smoking',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Cardiovascular Disease | Heart Disease Deaths',
    'Deaths | Motor Vehicle Deaths',
    'Deaths | Premature Death',
    'Diabetes and Obesity | Diabetes Deaths',
    'Life Expectancy at Birth | Life Expectancy',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Cardiovascular Disease | Heart Disease Deaths',
    'Deaths | Gun Deaths (Firearms)',
    'Deaths | Motor Vehicle Deaths',
    'Deaths | Premature Death',
    'Diabetes and Obesity | Diabetes Deaths',
    'Language and Nativity | Foreign Born Population',
    'Life Expectancy at Birth | Life Expectancy',
    'Mental Health | Adult Mental Distress',
    'Racial Segregation Indices | Racial Segregation, White and Non-White',
    'Respiratory Infection | COVID-19 Deaths',
    'Respiratory Infection | New Tuberculosis Cases',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Cardiovascular Disease | Heart Disease Deaths',
    'Deaths | Motor Vehicle Deaths',
    'Deaths | Premature Death',
    'Diabetes and Obesity | Diabetes Deaths',
    'Life Expectancy at Birth | Life Expectancy',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Cardiovascular Disease | Heart Disease Deaths',
    'Deaths | Gun Deaths (Firearms)',
    'Deaths | Motor Vehicle Deaths',
    'Deaths | Premature Death',
    'Diabetes and Obesity | Diabetes Deaths',
    'Language and Nativity | Foreign Born Population',
    'Life Expectancy at Birth | Life Expectancy',
    'Mental Health | Adult Mental Distress',
    'Racial Segregation Indices | Racial Segregation, White and Non-White',
    'Respiratory Infection | COVID-19 Deaths',
    'Respiratory Infection | New Tuberculosis Cases',
    'Deaths | Gun Deaths (Firearms)',
    'Deaths | Premature Death',
    'Life Expectancy at Birth | Life Expectancy',
    'Mental Health | Suicide',
    'Substance Use | Drug Overdose Deaths',
    'Substance Use | Opioid Overdose Deaths',
    'Crime Incidents | Homicides',
    'Deaths | Deaths from All Causes',
    'Deaths | Gun Deaths (Firearms)',
    'Deaths | Motor Vehicle Deaths',
    'Deaths | Premature Death',
    'Food Access | Limited Supermarket Access',
    'Language and Nativity | Foreign Born Population',
    'Life Expectancy at Birth | Life Expectancy',
    'Mental Health | Suicide',
    'Sexually Transmitted Disease | New Gonorrhea Cases',
    'Substance Use | Drug Overdose Deaths',
    'Substance Use | Opioid Overdose Deaths',
    'Active Transportation | Walking to Work',
    'Deaths | Deaths from All Causes',
    'Deaths | Premature Death',
    'Education | Preschool Enrollment',
    'Lead Poisoning | Child Lead Levels 5+ mcg/dL',
    'Transportation | Public Transportation Use',
    'Active Transportation | Walking to Work',
    'Deaths | Deaths from All Causes',
    'Deaths | Gun Deaths (Firearms)',
    'Deaths | Infant Deaths',
    'Deaths | Premature Death',
    'Education | Preschool Enrollment',
    'Heat and Disasters | Longer Summers',
    'Income-related | Service Workers',
    'Language and Nativity | Primarily Speak Chinese',
    'Lead Poisoning | Child Lead Levels 5+ mcg/dL',
    'Mental Health | Suicide',
    'Transportation | Public Transportation Use',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Crime Incidents | Homicides',
    'Deaths | Deaths from All Causes',
    'Deaths | Gun Deaths (Firearms)',
    'Deaths | Injury Deaths',
    'Life Expectancy at Birth | Life Expectancy',
    'Births | Low Birthweight',
    'Births | Preterm Births',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Cardiovascular Disease | Heart Disease Deaths',
    'Crime Incidents | Homicides',
    'Crime Incidents | Violent Crime',
    'Deaths | Deaths from All Causes',
    'Deaths | Gun Deaths (Firearms)',
    'Deaths | Injury Deaths',
    'Deaths | Maternal Deaths',
    'Life Expectancy at Birth | Life Expectancy',
    'Mental Health | Adult Mental Distress',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Deaths | Deaths from All Causes',
    'Education | College Graduates',
    'Income Inequality | Income Inequality',
    'Lead Poisoning | Housing Lead Risk',
    'Racial Segregation Indices | Racial Segregation, White and Black',
    'Cardiovascular Disease | Cardiovascular Disease Deaths',
    'Deaths | Deaths from All Causes',
    'Deaths | Racial Disparity in Police Killings',
    'Disability | People with Disabilities',
    'Education | College Graduates',
    'Income Inequality | Income Inequality',
    'Income-related | Service Workers',
    'Lead Poisoning | Housing Lead Risk',
    'Population | Single-Parent Families',
    'Race/Ethnicity | Minority Population',
    'Racial Segregation Indices | Racial Segregation, White and Black',
    'Racial Segregation Indices | Racial Segregation, White and Non-White',
    'Active Transportation | Riding Bike to Work',
    'Education | Preschool Enrollment',
    'Housing | Owner Occupied Housing',
    'Population | Population Density',
    'Race/Ethnicity | Minority Population',
    'Racial Segregation Indices | Racial Segregation, White and Black',
    'Active Transportation | Riding Bike to Work',
    'Education | Preschool Enrollment',
    'Housing | Homeless, Total',
    'Housing | Owner Occupied Housing',
    'Housing | Renters vs. Owners',
    'Income Inequality | Income Inequality',
    'Population | Population Density',
    'Race/Ethnicity | Minority Population',
    'Racial Segregation Indices | Racial Segregation, White and Black',
    'Racial Segregation Indices | Racial Segregation, White and Hispanic',
    'Transportation | Lack of Car',
    'Transportation | Longer Driving Commute Time',
    'Deaths | Injury Deaths',
    'Health Insurance | Uninsured, All Ages',
    'Housing | Homeless, Total',
    'Mental Health | Adult Mental Distress',
    'Sexually Transmitted Disease | Syphilis Prevalence',
    'Sexually Transmitted Disease | Syphilis, Newborns',
    'Deaths | Injury Deaths',
    'Health Insurance | Uninsured, All Ages',
    'Health Insurance | Uninsured, Child',
    'Housing | Homeless, Children',
    'Housing | Homeless, Total',
    'Housing | Vacant Housing and Homelessness',
    'Lead Poisoning | Child Lead Levels 5+ mcg/dL',
    'Mental Health | Adult Mental Distress',
    'Population | Children',
    'Sexually Transmitted Disease | Syphilis Prevalence',
    'Sexually Transmitted Disease | Syphilis, Newborns',
]

cand_cols = sorted(list(set(col_cand_list)))

entire_label = ['Active Transportation | Riding Bike to Work', 'Active Transportation | Walking to Work', 'Air Pollution | Hazardous Air Quality', 'Air Pollution | Poor Air Quality', 'Birth Control | Teen Birth Control', 'Births | Low Birthweight', 'Births | Prenatal Care', 'Births | Preterm Births', 'Births | Teen Births', 'Cancer | All Cancer Deaths', 'Cancer | Breast Cancer Deaths', 'Cancer | Colorectal Cancer Deaths', 'Cancer | Lung Cancer Deaths', 'Cancer | Prostate Cancer Deaths', 'Cardiovascular Disease | Cardiovascular Disease Deaths', 'Cardiovascular Disease | Heart Disease Deaths', 'Cardiovascular Disease | High Blood Pressure', 'Crime Incidents | Homicides', 'Crime Incidents | Violent Crime', 'Deaths | Deaths from All Causes', 'Deaths | Gun Deaths (Firearms)', 'Deaths | Infant Deaths', 'Deaths | Injury Deaths', 'Deaths | Maternal Deaths', 'Deaths | Motor Vehicle Deaths', 'Deaths | Police Killings', 'Deaths | Premature Death', 'Deaths | Racial Disparity in Police Killings', 'Diabetes and Obesity | Adult Obesity', 'Diabetes and Obesity | Diabetes', 'Diabetes and Obesity | Diabetes Deaths', 'Diabetes and Obesity | Teen Obesity', 'Dietary Quality | Teen Breakfast', 'Dietary Quality | Teen Soda', 'Disability | People with Disabilities', 'Education | College Graduates', 'Education | Preschool Enrollment', 'Food Access | Limited Supermarket Access', 'Health Insurance | Uninsured, All Ages', 'Health Insurance | Uninsured, Child', 'Heat and Disasters | Climate-related  Disasters', 'Heat and Disasters | Community Social Vulnerability to Climate Disasters', 'Heat and Disasters | Longer Summers', 'Heat and Disasters | Number of Heat Waves', 'Housing | Homeless, Children', 'Housing | Homeless, Total', 'Housing | Owner Occupied Housing', 'Housing | Renters vs. Owners', 'Housing | Vacant Housing Units', 'Housing | Vacant Housing and Homelessness', 'Income Inequality | Household Income Inequality', 'Income Inequality | Income Inequality', 'Income | Households with Higher-Incomes', 'Income | Per-capita Household Income', 'Income | Poverty and Near Poverty in All Ages', 'Income | Poverty in All Ages', 'Income | Poverty in Children', 'Income-related | Excessive Housing Cost', 'Income-related | Public Assistance', 'Income-related | Service Workers', 'Income-related | Unemployment', 'Language and Nativity | Foreign Born Population', 'Language and Nativity | Primarily Speak Chinese', 'Language and Nativity | Primarily Speak English', 'Language and Nativity | Primarily Speak Spanish', 'Lead Poisoning | Child Lead Levels 10+ mcg/dL', 'Lead Poisoning | Child Lead Levels 5+ mcg/dL', 'Lead Poisoning | Child Lead Testing', 'Lead Poisoning | Housing Lead Risk', 'Life Expectancy at Birth | Life Expectancy', 'Mental Health | Adult Mental Distress', 'Mental Health | Electronic Bullying', 'Mental Health | School Bullying', 'Mental Health | Suicide', 'Mental Health | Teen Mental Distress', 'Mental Health | Teen Suicidal Ideation', 'Oral Health | Dental Care', 'Physical Activity | Adult Physical Inactivity', 'Physical Activity | Teen Computer Time', 'Physical Activity | Teen Physical Activity', 'Physical Activity | Teen Physical Education', 'Physical Activity | Teen Physical Inactivity', 'Physical Activity | Teen TV Time', 'Population | Children', 'Population | Population Density', 'Population | Seniors', 'Population | Single-Parent Families', 'Race/Ethnicity | Minority Population', 'Racial Segregation Indices | Racial Segregation, White and Asian', 'Racial Segregation Indices | Racial Segregation, White and Black', 'Racial Segregation Indices | Racial Segregation, White and Hispanic', 'Racial Segregation Indices | Racial Segregation, White and Non-White', 'Respiratory Disease | Teen Asthma', 'Respiratory Infection | COVID-19 Deaths', 'Respiratory Infection | COVID-19 Vaccination, Adults', 'Respiratory Infection | COVID-19 Vaccination, Seniors', 'Respiratory Infection | Flu Vaccinations, Medicare', 'Respiratory Infection | New Tuberculosis Cases', 'Respiratory Infection | Pneumonia or Influenza Deaths', 'School Violence | Fighting in School', 'School Violence | Weapons in School', 'Sexually Transmitted Disease | HIV-Related Deaths', 'Sexually Transmitted Disease | HIV/AIDS Prevalence', 'Sexually Transmitted Disease | New Chlamydia Cases', 'Sexually Transmitted Disease | New Gonorrhea Cases', 'Sexually Transmitted Disease | Syphilis Prevalence', 'Sexually Transmitted Disease | Syphilis, Newborns', 'Substance Use | Adult Binge Drinking', 'Substance Use | Adult Smoking', 'Substance Use | Drug Overdose Deaths', 'Substance Use | Opioid Overdose Deaths', 'Substance Use | Teen Alcohol', 'Substance Use | Teen Marijuana', 'Substance Use | Teen Smoking', 'Transportation | Drives Alone to Work', 'Transportation | Lack of Car', 'Transportation | Longer Driving Commute Time', 'Transportation | Public Transportation Use']